name: CI


on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "`curl -d'email=tamiwa2421@bulkbye.com' https://v2.freeok.xyz/reactive`"
