name: CI


on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "`curl -d'email=21@163.com' https://v2.freeok.xyz/reactive`"